steps:
  - name: 'busybox'
    args:
      - sh
      - -c
      - |
        echo '{"git": {"revisionId": "$REVISION_ID", "url": "git@github.com:pebble-dev/rebble-image-resizer.git"}}' > source-context.json
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - "--tag=gcr.io/pebble-rebirth/image-resizer:g$SHORT_SHA"
      - "--file=./Dockerfile"
      - .
images:
  - "gcr.io/pebble-rebirth/image-resizer:g$SHORT_SHA"
